name: "Setup Diagrams Dependencies"
description: "Installs the dependencies for the diagrams"

runs:
  using: "composite"
  steps:
    - name: Install Python and UV
      uses: astral-sh/setup-uv@v5.3.1
      with:
        pyproject-file: "diagrams/pyproject.toml"
        enable-cache: true
    - name: Set up Just
      uses: extractions/setup-just@v2
    - name: Install Python Dependencies
      shell: bash
      run: just diagrams::install
