name: "Setup Diagrams Dependencies"
description: "Installs the dependencies for the diagrams"

runs:
  using: "composite"
  steps:
    - name: Install Python and UV
      uses: astral-sh/setup-uv@c7f87aa956e4c323abf06d5dec078e358f6b4d04 # v6.0.0
      with:
        working-directory: "diagrams"
    - name: Set up Just
      uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6 # v2.0.0
    - name: Install Python Dependencies
      shell: bash
      run: just diagrams::install
