# yaml-language-server: $schema=https://raw.githubusercontent.com/suzuki-shunsuke/pinact/refs/heads/main/json-schema/pinact.json
# pinact - https://github.com/suzuki-shunsuke/pinact
version: 3

ignore_actions:
  - name: actions/.*
    ref: .*
  - name: github/codeql-action/.*
    ref: .*
  - name: actions-js/push
    ref: .*
